### IMPORTANT: THIS FILE SHOULD BE NAMED THE SAME AS : ${MMN_BUSINESS_ACCOUNT_NAME} ###

server:
#  context-path: ${MMN_BUSINESS_ACCOUNT_CONTEXTPATH:accounts}
  port: ${MMN_BUSINESS_ACCOUNT_PORT:8181}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false

#security:
#  oauth2:
#    client:
#      clientId: ${MMN_BUSINESS_AUTH_NAME:business-auth-service}
#      clientSecret: ${MMN_BUSINESS_AUTH_PASSWORD:Password1234}
#
#      accessTokenUri: http://${MMN_BUSINESS_AUTH_HOST:localhost}:${MMN_BUSINESS_AUTH_PORT:8180}/${MMN_BUSINESS_AUTH_CONTEXTPATH:uaa}/oauth/token
#
#      grant-type: client_credentials
#      scope: server

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:application;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: false
    database: H2
    properties:
      hibernate:
      ddl-auto: update
      hbm2ddl.auto: update
  h2:
    console:
      enabled: true



# USING POSTGRESQL
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: developer
#    password: Password1234
#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: account
#        ddl-auto: update
#        hbm2ddl.auto: update

app.payment:
  clientId: "AZ2PlyKhOutjEaMwiRWfhWDV0riPkLbFS6m9XKPF-XV1QtUjkitkbv0RiHMrB5n1XQjpX0sUApulMuwb"
  clientSecret: "EADrmy6pdR_D5a_Ar9VYu2bDJZW78Ft0X912hlm_nQ9edqdO_7W6wrt6rgzECQHAfx4yhH3eRCA9rg6y"
  feign.url: "https://api.sandbox.paypal.com/v1/"

#spring:
#  data:
#    mongodb:
#      # shared database across services (can be improved)
#      host: ${MMN_MONGODB_HOST:localhost}
#      port: ${MMN_MONGODB_PORT:27017}
#      username: ${MMN_MONGODB_USER:user}
#      password: ${MMN_MONGODB_PASSWORD:Password1234}
#      database: ${MMN_MONGODB_DATABASE:mmn}
