### IMPORTANT: THIS FILE SHOULD BE NAMED THE SAME AS : ${MMN_BUSINESS_MAIL_NAME} ###

server:
#  context-path: ${MMN_BUSINESS_MAIL_CONTEXTPATH:mail}
  port: ${MMN_BUSINESS_MAIL_PORT:8184}

#security:
#  oauth2:
#    client:
#      clientId: ${MMN_BUSINESS_AUTH_NAME:business-auth-service}
#      clientSecret: ${MMN_BUSINESS_AUTH_PASSWORD:Password1234}
#
#      accessTokenUri: http://${MMN_BUSINESS_AUTH_HOST:localhost}:${MMN_BUSINESS_AUTH_PORT:8180}/${MMN_BUSINESS_AUTH_CONTEXTPATH:uaa}/oauth/token
#
#      grant-type: client_credentials
#      scope: server

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: jhmailbot
    password: zjdfzgvnvheppctb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
