package com.mmn.payment.model.type;

public enum ProductParamType {
	HOTELS,
	FLIGHTS,
	RENTAL_CARS,
	CRUISES,
	HOMES,
	WEEKS,
	MARKETPLACE,
	UNLIMITED_PASSPORTS_TO_SEND,
	IDECIDE_INTERACTIVE_SALES_SYSTEM,
	PERCENT_OF_REFERRAL_DIRECT_INVITATION,
	LEVEL_OF_REFERRAL_DIRECT_INVITATION,
	TRAVINED_ONLINE_BACK_OFFICE_MLM_MANAGEMENT,
	PERCENT_PASSPORTS_BONUSES 
}